sudo: false

language: python

python:
  - 2.7

install:
  - pip install coverage
  - pip install codecov

script:
  - python -m unittest discover
  - coverage run -m unittest discover
  - coverage html

after_success:
- codecov